spring:
  application:
    name: cucumber-example
  datasource:
    url: jdbc:h2:mem:lifeinsurancedb
    driverClassName: org.h2.Driver
    username: admin
    password: root
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
